---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nimtable-config
  namespace: proj10-platform
spec:
  encryptedData:
    config.yaml: AgCPugG4II5ESBkkAapCJn79R30dAV0fUzywlVtWq1z/3vKuDja2BncIvQzjIo+8AqfF+pdBKch1P+RSE/WUdM0zZTMwkpy1ZEkAwp4Ef2ol19PjRgdmStIulHiT0mv38s4rQxBvIylkMViy1BBfDfEUDGT+VIBq6efHhnEYFGvmfhNn9txNRQou2KR79voq+IsV//b7nl4/Foi5xC3EyhKJE0DCVBmQgtmo9ongq/mEjFOueVsenT7419qXo90mAidfJTSwzeyQpilZn3YLvQm9/4FipM0c9+GDf6+7E2TJnzHr1MOcvxGtjwnPBqF8JvvjNVpZReJC5wAOpMo8WfpDo+q55k/YnTWFzcdF+IQCHToXpG1DwagPij1/xB7RZUd1JeFIjoKaoxWSqDtRtY+dpziKhQwulxl6RAWmcp/zGu4mMA6PTbinY2XDqPSJCGg4G1kM8wpD9XkYNoa2CZjpPbGUzhUyox9BDGFM1KHjbVqCX7ah2mobD1A3S1WLlNqYlfhr2Qth4M/PiiGIYMLsiWQJijy6wuXdFeI03iSvIW/dZeajLfdjAiOglzf33rBsVzx4/wL4DKvH3MkpaE7joweW+VhTEqmZ2SupCX+NaKtzURHm11mH2Gq+GaSECuvjoqewpWk+XL+L44hI6IGLYxyYsAbzFA13eULIB62e58zXyRB//B+VUcxAR7IiZeUKfSoqB7t1pqvPZgWurAPwAEsOJH4mPpFBU5hFJefIAFIWJwvwh7p5ElPCH1mZLXI8HwgFACvr0XmC2ALJFq2osS8ccnAz888XQeUllCzM1rxfpeH2ogdjRs6QW9k1lyAEjpwcT3UF7jAJ9qexVF8w6t9VyAQ38M+DufCyv+sLKVQ0ECV3/i0HCr59hpp096Eas/ava0tYaOrvEzj4sZjC9A==
  template:
    metadata:
      name: nimtable-config
      namespace: proj10-platform
    type: Opaque
