---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: proj10-platform
spec:
  encryptedData:
    accesskey: AgAskKl6Owd2r/hb+SpnqBYf7DEq969Iy/D/qV8o41LEYFdprPbf5ycQP3cK4lk85lVEu0uxGiZQ9uaHKpm/lS98O7TRFEE9rTfL9jkK3CZyA2a2wcAi8xxjoVwZSZipB5OweNMRhNkBrMo4YkKSUsLTxretNj52i2zgTmwLINSFJDmEvhizB+IcRLIFAYeOq+yOcwiOBwbuZP10Rf9LMviQjDmRbYsxlJP3x7o1AaN1Td6XR891CVQ3324XpxhxA4M4Syd0sRxjJ2RP1DLpWLcKFFUaYWIcLgE95kEmydLhPgrSVp9oNNFN+kIA1Wu6E4+SJ9msi3g9i+rLTH4cGJ9SjSd30kamfjgsYjMjNH1ovwdUcC0aVByPbNNZ4DCKe28ADs8u+fYCeG2yGp4V++6XeGg+UzllD/hhd5Ol406n4lQ03SzxkXNgSsSsS0Ofon8MdlFTl7edAwn05xmiPuAVpOCbxFsA0BOIRXB2fJc278or33ubY/DkuXmPqbH5+Le5UgOdIi+603QG5Z2ofEFUm5mRCCh/tGJPm4DQzfMaqZF2tgA8FLpUdlmN0K6hr2hO8M1S3qjcFakhxUCeKamH4BJdPvQuLGb2SMyG3oigOETuIrLtJ5Oh7KcHL0n/mSAV0FPgmq/3rQ7ebK4k5hui4sQmI8+KkNZI3v0+AdNShhJ3mQSwHLgngCTMRvlLnL5YMlT66AVFJnH+58UbFZM=
    secretkey: AgDA3C9mGPLvajhUwGBqpZk0cdpyjMKAJpdWhnC4w79B/ewwfOQuSw4gc7v7AUIv0+omgJKFSixHzvz/G5CwWVNBToW3Xbi1AiNj8Fe1iVtd927I5+OV0drxKfG112P/iDmfHY7ZiMzO/QSbYHP4Ro1eVfSbYR/Q+We0Xsst7eN6JgGp4WZh2Dg5OoZQXaSj299zNbXY+Qrmc3Rwnhh4k0XW187pjS0WoII48Tvi1ooj1keRxJFygIkYl3woAnIJzp0+ZLIsdBbNi3NyLleNQySqZlFKCRSYg6FfZPr8T6n5KuRdTDgw+1PU80rZnJZ4eyVY3z1K1an5N8Uz1DSBwr/U/vhp7PG6BuBDczk+wqs+nnWtHQd+7eM4ieh8YGhuqFgtPdEJoe3nC5n8LexJmV0BQ7u1VlB4xzn5xNwjeh3UU68ssuanwXE4q7iTl0VyTqZQ7KGgY6y9Daq+uIMb9Kos/Fw15a7aT0nIbKW6n6aoLuULeedzRem0S5y5WxkhSXNxPfMYrpEWE1ap6pADshQIhrHPNgwovjzAJQwKMI9l7NzzCGSpTDfZRrOAcomB10vjAChQmo70mzfagmEZN2lUTw2y6fwbf3eEkHiRhhVwxsloNpScKYhGTAjdbXNAVkJVtFfkkX+bX1u41RfBHXU6HFsTCqXayx0TyhPjFo1k4z+HPLxD+5KS6C1XCuk3cK8bnm7Q2nKMI8+56IhZuoGB0PO6Ww==
  template:
    metadata:
      name: minio-credentials
      namespace: proj10-platform
    type: Opaque
