---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: proj10-platform
spec:
  encryptedData:
    accesskey: AgBJS7+5yfIQU9AGjMyTkf3qexV6uaaXr9VllTvHyFAlVkIPnxsd4FCzNkN137CLN0fogaLpNLDGh5dKHvWODQa3EE40kGabuLHJlzXnRSDyJ7fY70dE1FU2f33Sx1oq/YTihwtLX3FAV5n5nRzlBU6Krar8tK9jR7nyjs0Q0u/vOw4vfRVgjk4/ndEM/dG4bgB9607crmPy05hdIjGy2jqi2l79G4Cny5o1C/M4L9ocOxVs2WxuByy4tHWRV0IpakjGuNgSsBPSimO57G6T95zwpe+eSogRpqDYvP0kI3glTL2XLQnas2+HtyW0wAuNWtLTseCJwNy7vIYqTiYrfUYASWIQ7YByrRMUJd2QdUHT2waidDxeS8i7U1IoUzfoESjVo8xdivYFtkEwmDSaxvlCLBpxX57pHdzZq0NZbdFNEMBhhWZt8akdiqkpXmqQG6C+kai0ppBd3ji+HvNY8Gd9hZsVdBnC7cJHXxuqTYqWYdjkbr3+BDn6MDgWm1WEy0vkL6DfpNJq9yleZUoH+cbfjQUcYC9LsD8tdetRk1DRFiIzV4hQUFWjwEsu6u0jn63uFxv4N73dRb97E+zd+5vBH6X1oF5qlEVzggbmYhy/464+f/P66HKnLL6CCfNY48qcmq+sjGeRv6GHJCMfDgcdwrN/fteP5+bPVQZ11/mYqNhXsNYJz1QtJTu5Ys4w0FQ2xTxY7GD6tPV1SbuVnlfW
    secretkey: AgAWyJAE3lFK2C/ibbgUsUx+uNWF/+A6AT/60YqTMIGo2oLMjFr/MO+MdXcnNfmFYLdaKoKXwr20PxgnQCXuRn4/mEvBK7HJ+/qm4gqPGqc4ETsOSXYaXMLYYMTcMwOBBadE8xcgFHn1z8o+i3Jhs6yeoMinP50tS/wJeAMWQzC1TNAZ+ERW2i1gjuYcN1Vy7rcFNTmeu368ZiNn48+g2vTeLuYwSZs9BpETC0Wa/bMX5nM0sv3YsFfSsz+3oiuhS8p9whPxQN1fMY9Faj4srJC+6Xu3R8JIhyEC9Ic1hm1q6lnrP1PD5qh64jgzPoeLSpwdWNMsM2Pkq8v+zUlKrc+NBPw4+3Kh7P2Sgglkud02uuQoUgFZ7c0fDoMyAXcOjoN1gDfqKYvaQ42IEHO01Xs+QzYvN8DzsNZdjyf89vpquH8J3le2xGp1K4wSkpzvTmTtviRIf79ipdzt+3Qw6gYatQR0lpZIsFTv+Ghw5DGuCNHqE6KsajNpiWq0BTN4H+d4ZpBQBt2xtKbhglipNwulaiPQ4ux6JC2/jhXqQHnZgvgbh303/tcaGXr7nPzKOJpcX9dkhU/xCL26n0aLH314dbtpXq/7kNfyC0wisy3d+c6LCPLCFu6BA2m/mdh5AioFeZaGfJH+X0E0OAupfciYdbipJfIV/tDKaFrTknqdF62uUa4FtedizsAtDWk5G7iCQ5EtLNrOWH89j4LBAvqL
  template:
    metadata:
      name: minio-credentials
      namespace: proj10-platform
    type: Opaque
