---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: proj10-platform
spec:
  encryptedData:
    accesskey: AgBRBZgrMmMnP1MK1QWwIQbwGIrj8ZzNbDdteAskdIn8dVRNu3v3s26HYfrQDNnBMee0gGcOqvzOfauwAkkHtlvZtpVliaUW9ojVTuonVDB+yDNDdYHh5+Hu3MLg/CyCa+XUh9x5xc1EMoQu9xQcigml5upFk0iWLBhwDMt5v2nYOwCE7SBEUwtZQcLIWx/uKypfhciDrU55TXkQqxUHyouk+QswuuEetSN/TunVijRltLNqDgp9CWaecR+I9tJZDC2trKvXCH5GLbFhJHi/p9ZT/L4C41cXTDMZJPWVvHnj6Bbft/opGbkl6UnpPxqk+kAuQxPRPvtzFChOv6/+n4UIQps3OG4+Sa4TqbTdyO07wTlrY0Nzg9Tx8ay/NLHPC2Iu2LEkC72DzDp49M//IOivUBt6292+vpzVQCWoTJZ61YIM1US7kamRS+rj+aP0MbnMQCL0quN+varIMib9H0EDgkZ4WVVUph7byMKIw31gN/BYFfQ+cXk8oUYjdyV0fwn2QkJ2ZE5pbvzOK5quRGbrRMKVALqH+L8DYrOGG9Bu6zLuvLSxdfUrcPPzB0ZoM7B82l1/OlBQKgvzwNVRDHA9fMqIuieiO9ZyPGKivaMEK1CtgWxRd21NL/7j50nDOWmTd947A1rkexctr6aMyQLk7xEfb6K0Sfna+hAETzwXxMgZvc1O0zRkj6dO0MrCe0lsp7PJDnzJ0qt3eLUwYu3Z
    secretkey: AgAMhYu70+lNatzsUVaUUSwHRtU4jaYJ/MspAANbOaNA2lYaOIO04Rrj11yWV3HZNJ0WH/pnIam7M1RlGkSTRFrLRGi+dX8OA3hI4ymju0yUQtIKFvC5d8xAASebAAFa21iyCHIxAvatata90aXIGyuueB0qnnmGseRh/BQvyHHzz2W8UUU6Kdd/RPQb83V8jZEPAD4NRQbkdAvtvNF42yiya4g4UgxTRrheex2RRe/8S72izjyWcg+kjI6WflrsIIDcJtquSs8yhp/qPKWVPwYTJPtecFsLMM74421dxmfSsOROiV5efJ2BkXF4Ol+peMC3CehskuUK1QZLs5FvNBS6DPLOGFxKwLE68ed+bjBIz6/CfioxCep/n0A72niAj+gYPZSqQaTGxGngu9cgbK/BDMlUOZhOM2RnJB8jywkk+k3ynidfxf21CLCCG5fJi5oQSOt38gZEF0Cky4oYDzImX1ZyisUQo37baz872Q0OJL1wVUfz0EdqSoXNV8Fp0IUUZd/OqSVgFdS+9SKptviQKyXPSgsgA/jI1A8mX2iKDAXGMZUclyCjK2NKYS22KalrQLME7rHY85hdbLww1vyPhTvbxSJLgb1WjawkassjhCMUEQOMYUmr1WnwEoLRGf9dK1s6Zd1TiATLsL8goalGu3rLFYDdqUBPMVXj/KKVwzIP1MwIztNWfgXxcmQq3fF8+UPJH1iOiKKIT8UnCHAa
  template:
    metadata:
      name: minio-credentials
      namespace: proj10-platform
    type: Opaque
