---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nimtable-config
  namespace: proj10-platform
spec:
  encryptedData:
    config.yaml: AgCWCD/tbNN+jknKnOH44JVxR+Q/HKIJ7H8nuXnQIjTIUVRWCfxSBrgifzjLwWGc7/gpTxBzNpSPERHW+6AsmH71PynY6Cz70F6czuRUsFqa51M0KiPp4YQ4NlDIDycs8QUNuoumbKHB1Xs1AOpyQk/23lN7LVEjvyyFj08/YfhoIMJpUoHuaF4xBILYXzx+/rtYSQELhCDd8KKwU2ZpqhnuY5sHUVM/LkH60HI1aclMc8pUcWbWLrdHZurY2GUhnz6SKT+QqF27VuAnyybRc/y3l6KJu81q1piPe6NZleFlaFS53qwINEcfzBmeliLCObPxTg4OrDgdPPO36jaahCSIwWSEPJWjsmHsqh0iPY3Ksme0258jOVcudXHl4YH/B8tEEANp1LIKhbe6WU7URieVmnQFFvmjrLv//9XkcBBAUCqF2knFMT09hT7kaeeh610CMu9lGF9yb09mVjNsJaZqei467wzU3ju6is3rtkMLyJUx39xpBt4aMUsVIc++eHsBXyoycgwxBZhQa7l1EpVlFzo8QTX6dODb4QB4UZFzHTZQ8GZnlngzdlQEgfWbWvRbBfyLmDbDlRyBBGy8yuq5Z+d1wM6wAv/surSx/FPPJSdZBkE4fDWHs8j/xdTU9AGgg78tyNzN+y7BtadPBJTTJqwaZrsT7oZcS6ceHysRQ/6dTAMO18Y3qi3f8TLlW1LfUjGGNnsWazX/iHaOXjhUz/FTUy3lWvCqesqDp3YjkGtaoFqzso7VEY+JGOil6igl3hF35gqJ3ErcvZboReEscE0iXnRFP3NApOmdIOtBQGbop8eIsJG7jR5swtaAIDFCS+3L4jiONcLXEYNAIJA6nWSN3z4cEHH+3k81BTU753etkH50Ln+zhgB1auMDww1Sy7dd3ZHD6gkqOJoGWhG6IQFelOA72W5zHUozNkHRaPOVwxW4UU6x+TLAoqn+sdgs5NTZuQ0sGOA5jlmTetq4Ef5Ut77QiNVCiVhLiRzfdYgyYSXxVmS4QTkTbw==
  template:
    metadata:
      name: nimtable-config
      namespace: proj10-platform
    type: Opaque
