---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemspot-api
  namespace: proj10-platform
spec:
  encryptedData:
    GEMSPOT_API_KEY: AgChXH7dpBwF/LTZVEgjaoFFYUVdax6r2jfbm84GIBwTxEvuvPmCyytd1XtK/063+gx5JkURtLUrX3D2UIy4MIJoZzwM/0tRBFlGQCVspTevQ8dYiZBm8HYpl6UKU9MPmoPuFRZFRLpbYht88Uyk7q4Y/Qx4Me7B+XzH0it8tOXNmfwSD8NCuCqkIq5VhCEStSFbKjT6XX3pGVuDtxK5iSzrE3/bvlFk4DkCHY9elhzradYFhe+7OTy/XcLPLvVWj3tGZYM0HuwN5J/ZcIi2599tlk9qerCjugzYICV7fPVg2KoCAgaCJA1W0zt7CMyJMiV12eOqJNHR4q6eO8iNjKMPpHNc4zU16xMu9uLHu8diYxKYYBiMtgFhSKRCyNPo3473IBozLI54fp+AY5x0txlWvXB3CnGOH05gVPNx1lC8xb/glfqR+CtvXZpU6H17QvlskKk4p0rCpwX4sp/xN9OecW2F+gt2UwdBe65LIURurU5kp1nBcwwmi4lyM3Vw3xrGU+d9Xft4GAmPZpesxlatRSxD6TufqqT7rI6W6Ut87mF/hr0KG+auPtT/J2HZw3WcgKSqUTIEEe2ll9tZ23fi4zyKrqrwotV5ZwBl6JkKozCVazQVemL9bT8z0RZ6PYZ80bkNd0i5fue0sJgdAvcx92p8clgjCDwBo37uhBZRcVPxEX9CPw15o+8l5m4o5NGyebM3RxKpHuaWfOMkawqyJyzdTkACPFDonNT/D+kvEsMbdAQK54mRczU7Lztu
  template:
    metadata:
      name: gemspot-api
      namespace: proj10-platform
    type: Opaque
