---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nimtable-config
  namespace: proj10-platform
spec:
  encryptedData:
    config.yaml: AgC79sNUqoBGNeHKP9F60irGrdIN+etP0JOI6iyHU51AqgA8pkvFCrELl0B7iMOkV38knolY7NGnyGnvHMRyynAqeWPzoW0703WAhiiGzgypb0Anv3JmNOsKbA4f9Z0tOMeV11JpoyW7vM1sWUfZCzogL+WFZgz6N0dZNG+QIi2A+4VUxaV0KvIJvqYjjoAZOuKz+j5x7RzbjDTpal34QEBVOw/khvrlxoNpkQmhB1lTilUeBFzRGlbcdwBSEcQsE35d7eVApN6RprQLl8zVnfkmJWsWvU3YiMrSdBmWZvID6+kLMFGuxRkevkTbAYK6axpDCBi7DaQ/uTc31OZKXBDOlLJXkslk2HGnc/6Fa0XRno4Vin74R+x2ehWeyOw+uORjiEHtM+a87Or0Zv1DFOeeurr3gTX/On6pxqxbPmomyZg5pimhCF4PYMDAk3WCu6OUhn5Ofl/5m+9gqePtv3t8k9J/vUwA0JLz3BYapyqlBV9fsBHm7fHvfomH5tOmXR8pTz4aYOTHTqzyB/omG4ynVr7dD3LIMUPy7JnId3ts6PAlBvMFOuYbnfO9Hnt5INkFDpEA8zAndgGAxfbqx2K/2RDL3zkFPBesXDpYsH04jeh54K7YMjjVOsuRrr7qhEhs4LiHK/V2/AxzigEIU5fP+OarBFyg+ZBdwFqMsNfJtgrUs64rYwff25JYxw8aUq0O8HTknIMTlmxQ6QpQGITxpGBPKm8gsmD7UXabua4b374jFigOsGZR7JluG7AtnD1p7cCko+DfzpcKYr64M1o4njzRaBeqla/mAtKlwg6WJ9EC9b3N09rktwM9hCB/BDzSlI1oWjG8/snMG4AlbG9ctJ/hrsgcKMsWYEvyEaAtIhbcTN19WCXb3w7UXr7fMCdox5pnLt0BhOfCMA8cS0kou4DpnzifIEdEE9QrNKuM7Rgb6bpyv9n1hm0i7XAAXxXx5APUx+ALl8woHtDqA4HmMw==
  template:
    metadata:
      name: nimtable-config
      namespace: proj10-platform
    type: Opaque
