---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nimtable-config
  namespace: proj10-platform
spec:
  encryptedData:
    config.yaml: AgBGiDTYk2UAqQu3vODlVOFwqBqtbtJ3FJoKlg/HSQYqR/nLvfbAnN0OO7dsYK94IGW486vV3MZStDVZ3Kr1JrXaQnmk9gDxG1qnmWlJVgW3A3IadA91CemBQ9WorUjswkINwUqsIKSmW+GrWgVAl85XUps3MbQQTer9inYZdYwzxwo0E02SKmk446X4pk+NmwuQLjDzTSl1sBTqQJoXjWU/dN7EsFs5oQQ6w10tQQE6pMh+sbgUuCgqPlPjfZF8FZHspeAMflB49RhYBccA42ZCIDLqAzP3KX46h2N00XByo0mW1+2M6BhQk98057SVRmA3VIRilC+QQSru9tr3plzBsV1VIFzy5T0CUMr0xmz+QefwO8DSfJlymKHMkXbyAEk+V+6/kJ+zZrYtOMV0A1xeRT2mhgykYevQgRx+xk+m7+8Gc47DHg6RS54YEE7rx+QUXxho7UKvANUd/8BeFaRudjHD43t7ebuONYw8aCBMJLmLRTCgWbWsTOyfkxF78AMPzNRofosY8NIgww4T2eQPjpolmKAymvzttJ8Q8v4Yb7aj96oSJek6f29zkGT8nM0i8gUjZ3BrcObmAsTBWZXyv6lMFtfY9+qs7RMEzPDSbWvTL3xq8jtgc23RMLYvy/PTMNpX//5sLU+cG1yKmFuQ4G82RG9HlJxwHSM1Mj0CRx+k/p4bQ+xXM8nWeyxNKH4WfXrhpC2ZeC8az0NCQH8jFXiQSj4ZEnpo/6VemT09wDsIvLn9UztZ/b5vmcXTiUP8zVsoMaNds1Zonga3Glu/Q+LDme8gGhCXyzrH738XHUR5hA4I2KfVpzwQiF/gjVskV2fvPtmsJ2gZQI4MNTroDbiLDlqXTjug5x5lGtSmc3gl8elgkZxuFVliL/9fwBdfBan4NlNTjc1hhkeZB+wZVYuQC2HjH4oVd/V3yf3i4mC6+eKJ
  template:
    metadata:
      name: nimtable-config
      namespace: proj10-platform
    type: Opaque
