---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemspot-api
  namespace: proj10-platform
spec:
  encryptedData:
    GEMSPOT_API_KEY: AgBLjUSIARuNya8mAWVcVZNsXZSPxZzpgtVbHRrHIHzE6Q+FRVoY8Xzsyi9JwrO1dQxoIP80VMyIJlbiRz68Japf6cH8RFwl51EgBF6P8+/jIL53zC7WbpT79LXIlSHB60na0EKEQV7C7vchqcWFnDsBz7l1k7gkRYE5mylEdV7cn6XZVqkIeIvU8M7is4R0qRAVYmIZYwpv1tgtk9ZU5biir/duMGgAXHv+TB6i3Y/cz/z+rETfZogIb+L4XZuw2xIoV0VJqe2CtFRRBSqE+JggFGehn/6E6+I8Mu5uMRE9zVLry2Lx7HJX0bOYZIVpQMBxuLS6XNPTQtZP2quEAJDMyJb5tcsvPg7emAKpza4RaL5Hf/8HmqhfJMiD5HaIlZBzSkVhSrJ4uAv0x9ekw1u0rR8b0XqrnCPyF9hB5MOljEcUJ0f1S/MIEWuSyJGOZmWRIJPCgj/ClAnapBKaKECPT+peYXtNdoRNXT4T81LJ+/+imEqaDpHJ6aWojlxhudTVbXQGZBf/sT6OMCyw9FuiWXIfpRHla3uJHiQaTw0ul59jgExwR6r2lsjeixwBRY8Ls2nGgouDC7+oebqaBJ3KuVZTTUXb/d3fR9VFpZnlYlvpcTpMAH4mZdmHv1QBnmstTCjlroG55KzrCshdjRP1jmp/XntK/wI/1CQwAQ4QGwyXd4rEYyybfkrUaYWHq00qaYzWXrXnH7bJXjCq13HJn5I/QRMXWJ688motHADTKgZ3WSWTqso3zE2X3hgz
  template:
    metadata:
      name: gemspot-api
      namespace: proj10-platform
    type: Opaque
