---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: proj10-platform
spec:
  encryptedData:
    accesskey: AgBNq1ANaZNGF0Hl6EmyN+S5q11/mw6v1jUpKAjccgMWYCl9pttKHKdx6Kc4fK8JyKwSnmrFivYR1jx0aSYaRq8XItFn/tNcr9qqddzxXsymWY0Zrj0QbSchmsuPhtqPq5xMiaFjbCa7ab9MLRgLCTpF+RYCcXyXvIxDw+c18Cr7WJR5ljbkrRgo9QfLv3Pyca7zMHmyryXFpG14D2xAGrW7zuDtJkZzK8+RSdaeiRGRI9M/KLGszKBTNesd/fhSZ5UhoyU8gWnW16jgO9a6oCiyZS6DX1hsaD5aa4IJfDSdkEKD6V8WSLimUgqe2zEYaOILRKFrRRQY+Wj6ic5usZthpiPD5+uzA+jzyPPjruWMRlY1mo9R0HHAW1qaLOtfur8XVNgap+UN9UKrUcaqJtykCbkm0033Pkvb4/sL9vK11VCAmmtym87uQsGUChdYuRlqNqSEnZF8j78nDBAy28WCRA1iNBWO9LXBbRHMEcMteVrZuYI0N5LGUMSssS58zdxecRDake0b8JCvm5+3mg9/4KvmMTifQAG2hxKIwfYzIQ2m1ruNy1l8N5zP0Ynooqjfia0xEjIyoVrYOcOfpZN03/rEVy0vxJLhDW21pa/AziQ41Ke/YwehVIErJGZ8nZJwGzccTtiOUpKJYuH0VEKogM/bdKqMUprJOoG2lhG60B/Oqk+RvLhLCoiKbaUH0cvRc9iB1Qx6P5nujr9hUCEE
    secretkey: AgAoTxm2b4lnSnP6M5p8uDGwwv3FdZrXusumrik+CE82rwTANtZ1nHcHrJC8x3sdi9t1JDUBPRspT4TNDKwIANTbsmHHI3fAQioAXvs9auOcu8y1SRIR38EiioRE7JmLI/yjDnRa770KIWHHmO0T/n07yXpoGAwg6/rF9MdG7qe7Vn5xU1xPJ8CLoyepTDjBhKf/uAeauwHGARc3x8Amqr4p4MQQPRmws7XythEvFKnkHbhFzitvYdJqK0nUjDDcxwsugkkPKTK6uSlDZsPgt//f/CGldkbaC3wpGt0LBiqBzyjsUgcUv/Fw++kc//je9Eb0whLtgFCBgth1miqi9myK67AvXnRHIk4x/CF762MijKwZCusfjO6qtp3iYfzowSDa+6Jh1TT13belHHeB98F7Fjh1Q4UlLogYLOnqLQuVoz4qPXbdFg5m/Nsf3kAVM96M8TZyZx1WahI3WndoQV8VPO0kE9TRg70YhHujFOKF7jl7QosVhjXLs/NOsSVWEnbQka46s1gL4M+ZoxX3XBQKJwD7avvswEk/9cR+ArxxF9I09/VsXh48n7KSdbhIYjIicBn8NKS1xqvp7sErKq2BfWgOfQxk33s0knZ6W6K8tIvxKlO6oolNMYyN67W0UFFIowv1Mgp68d0L0YW35myQgShRz7fH/5kHjsuNSkRZY7oNxwNj7OnkIkNiDQdwPB+eCUTK3Hzjam3cxhJPCA0V
  template:
    metadata:
      name: minio-credentials
      namespace: proj10-platform
    type: Opaque
