---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemspot-api
  namespace: proj10-platform
spec:
  encryptedData:
    GEMSPOT_API_KEY: AgBBbCZ0w3wse4P2AGmJztrboA4TCeiJCE/g66NTJrfKaU2ekbBm133zTB78JIcIHjdwu4gDjTqAAoNQASW4WC78lxj9E/UST7K17rCV9JZRzwica35Prmiq716DCQ0QbkAbLsya96wK0XlOLZ3IdhB3Kq0skxmgOOK5tSkzw9rHP1xMJyJsBtpCjC5y7UXlUxVQR1ovfNawY0uTLsfpc6j5bXBml8CgbCVIO24eeJ6dnsRAXKRIMjpVEWunRRI5kv7u2QzAM4lbHOFgJskcJA9my+UfuVgOh1ZBcotJRu5rTWMbptt+1b+Aa2TVAjNS7kH/QTQ1qLBxTkI5xONO0W/9LVueCX38kRpEBY8EWveEXPVkzTG5LA+86Ru0Q7sLfl55SHgbKOlKt+GeZVjfvM8fsSmue9kfGxkB6eO0Bp8EemBEOv7qGkav04HpePXqzOCcuEluerR+p0ZlZg5RtJGmyzrRWXKSGHciTxpBjcn9RxjEUQfICd10Kxb6pEmdcJ6VgsaeRH0GmbXMrNzM5O6tb0Z9wrjHm7T+8cXxye4rsBWX+qglY1C8uIZI8C+4wK4iEORF1T0mcHwTYjf01NEwW6lBUxglNMWnHhK3LPHB48Fu3wkdt0q+oheIis06/rEA35A+fN8c+Rud5EcuSHlojulFd8hBqKhDOL94cXE5JS+XVVdOwsxpZMbb2Hjm1A5gy6X1Gz4xyaeg1ypngeHg/A7g/RSDd8MQv/lZTQbsWUn8Mgtzb2a6hX8Q7tGb
  template:
    metadata:
      name: gemspot-api
      namespace: proj10-platform
    type: Opaque
