{{- if .Values.redisInsight.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redisInsight.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redisInsight.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisInsight.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redisInsight.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redisInsight.name }}
    spec:
      containers:
        - name: redisinsight
          image: {{ .Values.redisInsight.image.repository }}:{{ .Values.redisInsight.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: RI_REDIS_HOST
              value: {{ .Values.redisInsight.env.redisHost | quote }}
            - name: RI_REDIS_PORT
              value: {{ .Values.redisInsight.env.redisPort | quote }}
            - name: RI_REDIS_ALIAS
              value: {{ .Values.redisInsight.env.redisAlias | quote }}
          ports:
            - name: http
              containerPort: 5540
          resources:
            {{- toYaml .Values.redisInsight.resources | nindent 12 }}
          volumeMounts:
            - name: redisinsight-storage
              mountPath: /data
      volumes:
        - name: redisinsight-storage
          persistentVolumeClaim:
            claimName: {{ .Values.redisInsight.name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisInsight.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.redisInsight.name }}
  ports:
    - name: http
      port: {{ .Values.redisInsight.service.port }}
      targetPort: http
  {{- if .Values.redisInsight.externalIP }}
  externalIPs:
    - {{ .Values.redisInsight.externalIP }}
  {{- end }}
{{- end }}
