frontend:
  replicaCount: 1
  image:
    repository: registry.kube-system.svc.cluster.local:5000/proj10-adventurelog-frontend
    tag: canary-latest
  service:
    port: 8081
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

backend:
  replicaCount: 1
  image:
    repository: registry.kube-system.svc.cluster.local:5000/proj10-adventurelog-backend
    tag: canary-latest
  service:
    port: 8000
    nginxPort: 80
  resources:
    limits:
      cpu: "500m"
      memory: "768Mi"
    requests:
      cpu: "250m"
      memory: "384Mi"

postgres:
  image:
    repository: postgis/postgis
    tag: "15-3.3"
  dbName: database
  user: adventure
  service:
    port: 5432
  storage:
    size: 10Gi
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"

persistence:
  media:
    size: 10Gi

service:
  # Injected by ArgoCD app set in ansible/argocd/argocd_add_*.yml
  externalIP: ""

app:
  publicUrl: "http://129.114.27.20:8081"
  frontendUrl: "http://129.114.27.20:8081"
  csrfTrustedOrigins: "http://129.114.27.20:8081"
  frontendBodySizeLimit: "Infinity"
  debug: "false"

secrets:
  existingSecret: "proj10-adventurelog-secrets"
